- name: Copy File, Build and Run Docker Container
  hosts: btj-academy
  become: true
  tasks:
    - name: copy Dockerfile
      ansible.builtin.copy:
        src: /home/muhammadrizqiakbar/task-ansible-2/Dockerfile
        dest: task-ansible-2
        mode: '0644'
    - name: copy app.py
      ansible.builtin.copy:
        src: /home/muhammadrizqiakbar/task-ansible-2/app.py
        dest: task-ansible-2
        mode: '0644'
    - name: copy requirements.txt
      ansible.builtin.copy:
        src: /home/muhammadrizqiakbar/task-ansible-2/requirements.txt
        dest: task-ansible-2
        mode: '0644'
    - name: build docker image
      ansible.builtin.command:
        cmd: 'docker build -t app-flask:0.1.0 task-ansible-2'
    - name: run docker container
      ansible.builtin.command:
        cmd: 'docker run -it -d --name flask-akbar -p 5007:5007 app-flask:0.1.0'
